[[redirects]]
  from = "/home"
  to = "/"
  status = 301
  force = false

[[redirects]]
  from = "/mentions-legales-1"
  to = "/mentions-legales"
  status = 301
  force = false

[[redirects]]
  from = "/cgv"
  to = "/conditions-generales-de-vente"
  status = 301
  force = false

[[redirects]]
  from = "/la-bibliothque"
  to = "/bibliotheque"
  status = 301
  force = false

[[redirects]]
  from = "/coo-chief-operating-officer-externalise"
  to = "/accompagnements-coo"
  status = 301
  force = false

[[redirects]]
  from = "/business-case-myblueprintvf"
  to = "/business-cases-conseil-en-pilotage-dentreprise/my-blueprintvf"
  status = 301
  force = false

[[redirects]]
  from = "/business-case-the-rising-court"
  to = "/business-cases-conseil-en-pilotage-dentreprise/business-case-the-rising-court"
  status = 301
  force = false

[[redirects]]
  from = "/business-case-embrace-planner"
  to = "/business-cases-conseil-en-pilotage-dentreprise/business-case-embrace-planner"
  status = 301
  force = false

